### ISSUE TITLE
CWL support with Calrissian on k8s: Find stable solution for RWX volume requirement

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#1006]
as observed during the PoC development under #936 for https://github.com/EOEPCA/roadmap/issues/41: the current RWX volumes we have for calrissian (as initially set up in https://github.com/eu-cdse/openeo-cdse-infra/issues/267)  are pretty unstable. We need to figure out a solution to have stable RWX support

**Comment by jdries** [comment]
Is the issue still present with S3FS volume type? If under control, I propose to postpone this at least to the next eoepca cycle.

**Comment by tcassaert** [comment]
As there's little confidence in the stability of the Swift Object Storage, JuiceFS will not be used. Given the complexity of Ceph, I think the main options now are OpenEBS and Longhorn.

**Comment by tcassaert** [comment]
To limit the complexity further, we opted for the most simple solution, an NFS server backed by an OpenStack Cinder volume. The PV and PVC are created and managed by https://github.com/kubernetes-csi/csi-driver-nfs.

The NFS server setup:
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server
  namespace: nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-cinder-sc-retain-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-server
      restartPolicy: Always
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine
        env:
        - name: SHARED_DIRECTORY
          value: /nfsshare
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /nfsshare
            name: nfs-vol
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs
spec:
  ports:
    - name: nfs
      port: 2049
  selector:
    role: nfs-server
```

A new StorageClass was created to support SSD Cinder volumes for better performance of the NFS server.

Then the `csi-driver-nfs` was deployed as follows:

```bash
helm upgrade --install nfs-csi --create-namespace -n nfs csi-driver-nfs/csi-driver-nfs --values values_nfs_csi.yam
```
The values file looks like:
```yaml
---
image:
  baseRepo: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache
  nfs:
    repository: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache/sig-storage/nfsplugin
    tag: v4.11.0
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache/sig-storage/csi-provisioner
    tag: v5.2.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache/sig-storage/csi-resizer
    tag: v1.13.1
    pullPolicy: IfNotPresent
  csiSnapshotter:
    repository: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache/sig-storage/csi-snapshotter
    tag: v8.2.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache/sig-storage/livenessprobe
    tag: v2.15.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache/sig-storage/csi-node-driver-registrar
    tag: v2.13.0
    pullPolicy: IfNotPresent
  externalSnapshotter:
    repository: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/registry-k8s-cache/sig-storage/snapshot-controller
    tag: v8.2.0
    pullPolicy: IfNotPresent
controller:
  nodeSelector:
    system-services-node: "true"
  tolerations:
    - key: "system-services-node"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  workingMountDir: /tmp
storageClass:
  create: true
  name: csi-nfs
  parameters:
    server: nfs-server.nfs.svc.cluster.local
    share: /
    subDir: "cwl/${pvc.metadata.name}"
    mountPermissions: "0"
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=4.1
```

A new StorageClass is created by the Helm chart, that we can use in the PVC creation:
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calrissian-input-data-nfs
  namespace: calrissian-demo-project
spec:
  storageClassName: csi-nfs
  accessModes: ["ReadWriteOnce", "ReadOnlyMany"]
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calrissian-tmpout-nfs
  namespace: calrissian-demo-project
spec:
  storageClassName: csi-nfs
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calrissian-output-data-nfs
  namespace: calrissian-demo-project
spec:
  storageClassName: csi-nfs
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 5Gi
```

A simple test workflow:

```bash
#!/usr/bin/env bash
count=10
for (( i=0; i<$count; i++ )); do
  kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  name: cwl-rwx-test-job-$i
  namespace: calrissian-demo-project
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      initContainers:
      - name: cwl-rwx-test-job-init-$i
        image: registry.stag.waw3-1.openeo-int.v1.dataspace.copernicus.eu/rand/alpine:3
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - set -euxo pipefail;echo 'Y3dsVmVyc2lvbjogdjEuMApjbGFzczogQ29tbWFuZExpbmVUb29sCgojIFRoaXMgQ1dMIHVzZXMgYSBEb2NrZXIgaW1hZ2UgdGhhdCB3YXMgYnVpbHQgZnJvbSB0aGlzIERvY2tlcmZpbGU6CiMgaHR0cHM6Ly9naXRodWIuY29tL09wZW4tRU8vb3BlbmVvLWdlb3B5c3BhcmstZHJpdmVyL2Jsb2IvYjY1MzM1MTg0YjIwNTBmZjM4Y2U2OTk3YTBkNDM0NGMyMjdjZWM5Zi9kb2NrZXIvbG9jYWxfYmF0Y2hfam9iL2V4YW1wbGVfc3RhY19jYXRhbG9nL0RvY2tlcmZpbGUKIyBJdCdzIGEgdmVyeSBzaW1wbGUgaW1hZ2UgdGhhdCBqdXN0IHBhY2thZ2VzIHNvbWUgSlNPTiBhbmQgVElGRiBmaWxlcwojIGZyb20gdGhlIGV4YW1wbGUgU1RBQyBjb2xsZWN0aW9uIGF0IGh0dHBzOi8vZ2l0aHViLmNvbS9PcGVuLUVPL29wZW5lby1nZW9weXNwYXJrLWRyaXZlci90cmVlL2I2NTMzNTE4NGIyMDUwZmYzOGNlNjk5N2EwZDQzNDRjMjI3Y2VjOWYvZG9ja2VyL2xvY2FsX2JhdGNoX2pvYi9leGFtcGxlX3N0YWNfY2F0YWxvZwojIFRoaXMgQ1dMIGp1c3QgZXh0cmFjdHMgdGhlc2UgcmVzb3VyY2VzIGFnYWluIGFuZCBwcm92aWRlcyB0aGVtIGFzIENXTCBvdXRwdXQuCgpyZXF1aXJlbWVudHM6CiAgLSBjbGFzczogRG9ja2VyUmVxdWlyZW1lbnQKICAgIGRvY2tlclB1bGw6IHZpdG8tZG9ja2VyLmFydGlmYWN0b3J5LnZndC52aXRvLmJlL29wZW5lby1nZW9weXNwYXJrLWRyaXZlci1leGFtcGxlLXN0YWMtY2F0YWxvZzoxLjAKCmJhc2VDb21tYW5kOiBbInNoIiwgIi1jIiwgImNwIC9kYXRhLyogLiJdCmlucHV0czogW10Kb3V0cHV0czoKICBvdXRwdXQ6CiAgICB0eXBlOgogICAgICB0eXBlOiBhcnJheQogICAgICBpdGVtczogRmlsZQogICAgb3V0cHV0QmluZGluZzoKICAgICAgZ2xvYjogWyIqLmpzb24iLCAiKi50aWYiLCAiKi50aWZmIl0K' | base64 -d > /calrissian/input-data/cwl-rwx-test-job-$i.cwl
        volumeMounts:
        - mountPath: /calrissian/input-data
          name: calrissian-input-data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      containers:
      - name: cwl-rwx-test-job-$i
        image: ghcr.io/duke-gcb/calrissian/calrissian:0.17.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            calrissian --debug --max-ram 15G --max-cores 4 --force-docker-pull
            --tmp-outdir-prefix /calrissian/tmpout/
            --outdir /calrissian/output-data/cwl-rwx-test-job-$i
            --stdout /calrissian/output-data/cwl-rwx-test-job-$i/cwl-outputs.json
            /calrissian/input-data/cwl-rwx-test-job-$i.cwl
        env:
        - name: CALRISSIAN_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /calrissian/input-data
          name: calrissian-input-data
          readOnly: true
        - mountPath: /calrissian/tmpout
          name: calrissian-tmpout
        - mountPath: /calrissian/output-data
          name: calrissian-output-data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      restartPolicy: Never
      volumes:
      - name: calrissian-input-data
        persistentVolumeClaim:
          claimName: calrissian-input-data-nfs
      - name: calrissian-tmpout
        persistentVolumeClaim:
          claimName: calrissian-tmpout-nfs
      - name: calrissian-output-data
        persistentVolumeClaim:
          claimName: calrissian-output-data-nfs
EOF
done
```

The base64 encoded string contains:
```cwl
cwlVersion: v1.0
class: CommandLineTool

# This CWL uses a Docker image that was built from this Dockerfile:
# https://github.com/Open-EO/openeo-geopyspark-driver/blob/b65335184b2050ff38ce6997a0d4344c227cec9f/docker/local_batch_job/example_stac_catalog/Dockerfile
# It's a very simple image that just packages some JSON and TIFF files
# from the example STAC collection at https://github.com/Open-EO/openeo-geopyspark-driver/tree/b65335184b2050ff38ce6997a0d4344c227cec9f/docker/local_batch_job/example_stac_catalog
# This CWL just extracts these resources again and provides them as CWL output.

requirements:
  - class: DockerRequirement
    dockerPull: vito-docker.artifactory.vgt.vito.be/openeo-geopyspark-driver-example-stac-catalog:1.0

baseCommand: ["sh", "-c", "cp /data/* ."]
inputs: []
outputs:
  output:
    type:
      type: array
      items: File
    outputBinding:
      glob: ["*.json", "*.tif", "*.tiff"]
```

This creates 10 jobs, that all use the same PVCs. These all succeed without issue, so the RWX volumes work. Throughput testing was not yet performed.
