### ISSUE TITLE
Invoke SNAP on master/slave pairs store to readable format (Zarr, Geotiff)

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geopyspark-driver#1034]
Duplicate of https://github.com/cloudinsar/s1-workflows/issues/3

**Comment by EmileSonneveld** [comment]
Not all PVCs need to be s3 mounted in local tests. This might give better performance on CDSE staging:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-input-data
  namespace: calrissian-demo-project
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-tmpout
  namespace: calrissian-demo-project
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-output-data
  namespace: calrissian-demo-project
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-s3-calrissian
```
