### ISSUE TITLE
gamma0/sar_backscatter via SNAP 

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#1137]
With support for SNAP in CWL now working, it should be fairly easy to generated CARD4L compliant gamm0 backscatter.
This method from pyrosar is what has been used elsewhere:
https://pyrosar.readthedocs.io/en/latest/api/snap.html#pyroSAR.snap.util.geocode

If we can extract the snap graph(s) that it generates, they are probably usable in a CWL. Other option is to just use pyrosar directly, as it has some nice performance improvements.

**Comment by JeroenVerstraelen** [comment]
Only works for one product at a time at the moment

**Comment by jdries** [comment]
Here's yet another alternative, also based on SNAP, but batch support is built-in as well as CEOS ARD support:
https://opensartoolkit.readthedocs.io/en/latest/example/S1_GRD_batch_subset.html

**Comment by jdries** [comment]
@EmileSonneveld the first thing that we need from this is very simple:
- reference output for gamma0-terrain (ceos ard) in both hilly and flat region
- timings for those reference outputs, giving us an idea of the relative cost compared to orfeo approach

**Comment by EmileSonneveld** [comment]
With some experimenting, this 11Gb output was made:
![Image](https://github.com/user-attachments/assets/6778333b-973c-467c-95b2-5842f709c578)
For input, I used: `S1B_IW_GRDH_1SDV_20200606T060615_20200606T060640_021909_029944_4C69.zip `. Made by zipping the relevant .SAFE directory
`cwltool resources/opensar.cwl#opensartoolkit /path/to/filled/input.yml`
Content of input.yml:
```yaml
---
input:
  class: Directory
  path: /path/to/OpenSarToolkit/examples/application-package/SAR/GRD/2022/10/04/
resolution: 100
ard-type: CEOS
with-speckle-filter: true
resampling-method: BILINEAR_INTERPOLATION
cdse-user: ***
cdse-password: ***
dry-run: false
```

To make this work I had to instal a different docker package too:
```bash
sudo snap remove docker --purge
sudo apt install -y docker.io
```
Going to compare with test_creodias_s1_backscatter now...
